/**
 * Telegram Service
 * Sends alerts and system notifications to users
 */

import TelegramBot from 'node-telegram-bot-api';
import { config } from '../config.js';

let bot: TelegramBot | null = null;

export async function initTelegram(): Promise<void> {
  if (!config.telegramBotToken) {
    throw new Error('Telegram bot token not configured');
  }

  bot = new TelegramBot(config.telegramBotToken, { polling: false });

  // Verify bot is working
  try {
    const me = await bot.getMe();
    console.log(`✅ Telegram bot initialized: @${me.username}`);
  } catch (error) {
    console.error('❌ Telegram bot initialization failed:', error);
    throw error;
  }
}

/**
 * Format price with currency
 */
function formatPrice(price: number): string {
  return `$${price.toFixed(2)}`;
}

/**
 * Format percentage
 */
function formatPercent(percent: number): string {
  const sign = percent >= 0 ? '+' : '';
  return `${sign}${percent.toFixed(1)}%`;
}

/**
 * Send alert notification
 */
export async function sendAlert(alert: {
  symbol: string;
  type: string;
  price: number;
  stopLoss?: number;
  target1?: number;
  target2?: number;
  confidence?: number;
  message?: string;
}): Promise<void> {
  if (!bot || !config.telegramChatId) {
    console.log('⚠️ Telegram not configured, skipping alert notification');
    return;
  }

  const emoji = alert.type === 'TRIGGERED' ? '🎯' :
                 alert.type === 'intraday_spark' ? '⚡' :
                 alert.type === 'swing_entry' ? '📈' :
                 alert.type === 'dual_pullback' ? '🎯' : '🔔';

  let message = `
${emoji} <b>ALERT: ${alert.symbol}</b>

📊 <b>Type:</b> ${alert.type.toUpperCase()}
💰 <b>Entry:</b> ${formatPrice(alert.price)}
`;

  if (alert.stopLoss) {
    const riskPercent = ((alert.price - alert.stopLoss) / alert.price * 100).toFixed(1);
    message += `🛡️ <b>Stop:</b> ${formatPrice(alert.stopLoss)} (${riskPercent}% risk)
`;
  }

  if (alert.target1) {
    const rewardPercent = ((alert.target1 - alert.price) / alert.price * 100).toFixed(1);
    message += `🎯 <b>Target 1:</b> ${formatPrice(alert.target1)} (${rewardPercent}% reward)
`;
  }

  if (alert.target2) {
    message += `🎯 <b>Target 2:</b> ${formatPrice(alert.target2)}
`;
  }

  if (alert.confidence) {
    const confPercent = Math.round(alert.confidence * 100);
    const confEmoji = confPercent >= 85 ? '🔥' : confPercent >= 70 ? '⭐' : '📊';
    message += `${confEmoji} <b>Confidence:</b> ${confPercent}%
`;
  }

  if (alert.message) {
    message += `\n📝 ${alert.message}`;
  }

  message += `\n\n<i>Generated by FinScreener Pro</i>`;

  try {
    await bot.sendMessage(config.telegramChatId, message, { parse_mode: 'HTML' });
    console.log(`📱 Telegram alert sent: ${alert.symbol}`);
  } catch (error) {
    console.error('Failed to send Telegram alert:', error);
  }
}

/**
 * Send trade update notification
 */
export async function sendTradeUpdate(update: {
  symbol: string;
  action: 'ENTRY' | 'EXIT' | 'UPDATE';
  price: number;
  pnl?: number;
  reason?: string;
}): Promise<void> {
  if (!bot || !config.telegramChatId) {
    return;
  }

  const actionEmoji = update.action === 'ENTRY' ? '✅' :
                      update.action === 'EXIT' ? '🚪' : '🔄';

  let message = `
${actionEmoji} <b>TRADE ${update.action}: ${update.symbol}</b>

💰 <b>Price:</b> ${formatPrice(update.price)}
`;

  if (update.pnl !== undefined) {
    const pnlEmoji = update.pnl >= 0 ? '💚' : '💔';
    message += `${pnlEmoji} <b>P&L:</b> ${formatPrice(update.pnl)}
`;
  }

  if (update.reason) {
    message += `\n📝 <b>Reason:</b> ${update.reason}`;
  }

  try {
    await bot.sendMessage(config.telegramChatId, message, { parse_mode: 'HTML' });
  } catch (error) {
    console.error('Failed to send trade update:', error);
  }
}

/**
 * Send daily summary
 */
export async function sendDailySummary(summary: {
  totalAlerts: number;
  triggeredAlerts: number;
  avgPnL: number;
  topGainer?: { symbol: string; pnl: number };
  topLoser?: { symbol: string; pnl: number };
}): Promise<void> {
  if (!bot || !config.telegramChatId) {
    return;
  }

  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let message = `
📊 <b>DAILY SUMMARY</b>
<i>${date}</i>

📈 <b>Alerts:</b> ${summary.triggeredAlerts}/${summary.totalAlerts} triggered
💰 <b>Avg P&L:</b> ${formatPrice(summary.avgPnL)}
`;

  if (summary.topGainer) {
    message += `\n🟢 <b>Top Gainer:</b> ${summary.topGainer.symbol} ${formatPrice(summary.topGainer.pnl)}`;
  }

  if (summary.topLoser) {
    message += `\n🔴 <b>Top Loser:</b> ${summary.topLoser.symbol} ${formatPrice(summary.topLoser.pnl)}`;
  }

  message += `\n\n<i>Generated by FinScreener Pro</i>`;

  try {
    await bot.sendMessage(config.telegramChatId, message, { parse_mode: 'HTML' });
    console.log('📱 Daily summary sent to Telegram');
  } catch (error) {
    console.error('Failed to send daily summary:', error);
  }
}

/**
 * Send system status notification
 */
export async function sendSystemStatus(
  status: 'started' | 'stopped' | 'error' | 'warning' | 'info',
  message: string
): Promise<void> {
  if (!bot || !config.telegramChatId) {
    return;
  }

  const statusEmoji = {
    started: '🟢',
    stopped: '⚫',
    error: '🔴',
    warning: '⚠️',
    info: 'ℹ️',
  }[status];

  const fullMessage = `
${statusEmoji} <b>SYSTEM ${status.toUpperCase()}</b>

${message}

⏰ ${new Date().toLocaleString()}
`;

  try {
    await bot.sendMessage(config.telegramChatId, fullMessage, { parse_mode: 'HTML' });
  } catch (error) {
    console.error('Failed to send system status:', error);
  }
}

/**
 * Send market open/close notification
 */
export async function sendMarketNotification(
  type: 'open' | 'close' | 'pre_market' | 'after_hours'
): Promise<void> {
  if (!bot || !config.telegramChatId) {
    return;
  }

  const messages = {
    open: '🔔 <b>MARKET OPEN</b>\n\nTrading session is now active. Good luck!',
    close: '🔕 <b>MARKET CLOSE</b>\n\nTrading session has ended.',
    pre_market: '🌅 <b>PRE-MARKET</b>\n\nExtended hours trading begins.',
    after_hours: '🌙 <b>AFTER HOURS</b>\n\nExtended hours trading active.',
  };

  try {
    await bot.sendMessage(config.telegramChatId, messages[type], { parse_mode: 'HTML' });
  } catch (error) {
    console.error('Failed to send market notification:', error);
  }
}
